apiVersion: v2
name: example
type: application
version: 0.0.0
appVersion: "latest"

dependencies:
  - name: grafana-agent
    version: "0.42.*" # old version of grafana-agent subchart
    repository: https://grafana.github.io/helm-charts
    condition: grafana-agent.enabled
