name: CI
"on":
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - main
      - release-*

jobs:
  check-generated:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: |
          make
          git diff --exit-code
